---
title: "Regression Tree - Example on Insurance data"
output: html_document
date: '2022-10-21'
---

```{r setup, include=FALSE}
# Define columnn class for dataset
colCls <- c("integer",         # row id
            "character",       # analysis year
            "numeric",         # exposure
            "character",       # new business / renewal business
            "numeric",         # driver age (continuous)
            "character",       # driver age (categorical)
            "character",       # driver gender
            "character",       # marital status
            "numeric",         # years licensed (continuous)
            "character",       # years licensed (categorical)
            "character",       # ncd level
            "character",       # region
            "character",       # body code
            "numeric",         # vehicle age (continuous)
            "character",       # vehicle age (categorical)
            "numeric",         # vehicle value
            "character",       # seats
            rep("numeric", 6), # ccm, hp, weight, length, width, height (all continuous)
            "character",       # fuel type
            rep("numeric", 3)  # prior claims, claim count, claim incurred (all continuous)
)

# Define the data path and filename
data.path <- "C:\\Users\\William.Tiritilli\\Documents\\Project P\\Book - Predictive Modeling vol1&2 - Frees\\Tome 2 - Chapter 1\\"
data.fn <- "sim-modeling-dataset2.csv"

# Read in the data with the appropriate column classes
dta <- read.csv(paste(data.path, data.fn, sep = "/"),
                colClasses = colCls)
str(dta)

```


```{r}
set.seed(1234) # reproducibility
# Create a stratified data partition
train_id <- caret::createDataPartition(
  y = dta$clm.count/dta$exposure,
  p = 0.8,
  groups = 100
)[[1]]

```


```{r}
# Divide the data in training and test set
dta_trn <- dta[train_id,]
dta_tst <- dta[-train_id,]

library(dplyr)
# Proportions of the number of claims in train data
dta_trn$clm.count %>% table %>% prop.table %>% round(5)
# Proportions of the number of claims in test data
dta_tst$clm.count %>% table %>% prop.table %>% round(5)
```


```{r}
##################################################
## Regression Tree: claims frequency estimation ##
##################################################

library(rpart)       # direct engine for decision tree application
library(caret)       # meta engine for decision tree application
fit <- rpart(formula = 
               cbind(exposure,clm.count) ~ # Response as a 2-column matrix
               driver.age  + hp
             + fuel.type + driver.gender + body.code + yrs.licensed,
             data = dta_trn,
             method = 'poisson', # To express the Poisson Deviance
             control = rpart.control(
               maxdepth = 3,
               cp = 0 )
)
print(fit)

# We observe that the most important variable that
# has the largest reduction of the Poisson Deviance is 'yrs.licensed'
# Here the split is performed at 4.5 years of driving experience.



```

```{r}
# Graph
library(rpart.plot)
rpart.plot(fit, type = 1, cex = 0.70)


plotcp(fit)


```

```{r}

# Use of the package vip
var_imp <- vip::vi(fit)
print(var_imp)

# Function vip makes the plot
vip::vip(fit, scale = TRUE)




```

